#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=50
#SBATCH --mem-per-cpu=4G
#SBATCH --job-name=trainNetworks
#SBATCH --time=6:00:00

module purge

source $HOME/.envs/ML_Final/bin/activate
python --version

python main.py
