#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=50
#SBATCH --mem-per-cpu=2G
#SBATCH --job-name=network_evaluator
#SBATCH --time=4-12:00:00

module purge
module load Python

srun pip install -r requirements.txt
srun python main.py