#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=50
#SBATCH --mem-per-cpu=2G
#SBATCH --job-name=trainNetworks
#SBATCH --time=4-12:00:00
#SBATCH --output=/scratch/s4950836/%j.out

module purge
module load Python

srun python main.py